server:
  port: 8099

spring:
  application:
    name: service-book
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
mybatis:
  type-aliases-package: com.jk.model
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-locations: classpath:mybatis/confg.xml
