eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/


spring:
  application:
    name: service-feign1
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html

feign:
  hystrix:
    enabled: true
